/* generated by naming.py -- piece candidate names with plausibility ranks */
#define NP 14
static const char *PKEY[NP]={"calendar","gnome","africa","bow","oman","feast","rect","frames","barn","chart","snow","joy","eagle","p14"};
#define MAXOPT 16
static const int NOPT[NP]={10,11,14,11,7,7,16,15,9,10,8,8,11,9};
static const int OR_[NP][MAXOPT]={
  {0,1,2,3,4,5,6,7,8,9},
  {0,1,2,3,4,5,6,7,8,9,10},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13},
  {0,1,2,3,4,5,6,7,8,9,10},
  {0,1,2,3,4,5,6},
  {0,1,2,3,4,5,6},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14},
  {0,1,2,3,4,5,6,7,8},
  {0,1,2,3,4,5,6,7,8,9},
  {0,1,2,3,4,5,6,7},
  {0,1,2,3,4,5,6,7},
  {0,1,2,3,4,5,6,7,8,9,10},
  {0,1,2,3,4,5,6,7,8},
};
static const char OL_[NP][MAXOPT]={
  {'A','A','E','P','E','O','H','E','A','D'},
  {'A','A','H','H','L','I','A','A','O','N','H'},
  {'T','O','I','H','T','T','S','I','D','E','U','I','A','A'},
  {'S','E','L','T','L','B','O','B','L','I','N'},
  {'F','L','M','F','T','N','A'},
  {'A','A','A','L','L','S','B'},
  {'S','N','C','C','N','R','U','D','O','I','W','L','D','R','O','E'},
  {'T','B','C','E','P','S','P','S','D','T','A','D','S','S','F'},
  {'A','A','I','S','A','U','N','A','R'},
  {'H','C','O','I','D','C','T','D','I','A'},
  {'H','D','E','M','E','L','W','U'},
  {'E','Y','R','G','Y','I','T','A'},
  {'G','C','E','H','A','A','D','N','D','E','A'},
  {'I','C','G','A','N','P','E','E','O'},
};
static const char OB_[NP][MAXOPT]={
  {'E','E','K','R','R','E','I','E','E','E'},
  {'E','E','L','N','E','D','S','F','E','R','L'},
  {'N','R','C','T','L','N','A','N','G','Y','R','B','H','C'},
  {'S','F','S','C','S','W','B','W','C','G','T'},
  {'O','F','O','I','A','A','L'},
  {'A','A','A','L','L','S','B'},
  {'U','L','A','T','Q','C','R','O','K','K','L','T','O','E','K','Q'},
  {'M','F','F','P','F','W','W','W','C','M','S','T','B','D','C'},
  {'R','R','G','T','R','M','R','L','G'},
  {'A','R','W','N','S','R','D','C','C','M'},
  {'D','C','F','S','S','I','T','Y'},
  {'O','J','G','G','E','E','L','I'},
  {'E','L','G','A','E','L','A','R','A','G','D'},
  {'?','?','?','?','?','?','?','?','?'},
};
static const char *ONM[NP][MAXOPT]={
  {"calendar","calendar page","desk calendar","spiral calendar","tear off calendar","notepad","christmas","december","date","advent calendar"},
  {"santas helper","garden gnome","christmas elf","christmas gnome","elf on the shelf","gingerbread man","father christmas","garden dwarf","roller skate","snowboarder","christmas elves"},
  {"continent","map of africa","african continent","silhouette","potted plant","thatching","houseplant","africa and plant","seedling","greenery","shrubbery","african bush","savannah","madagascar"},
  {"glasses","butterfly","eyeglasses","spectacles","sunglasses","hair bow","ribbon bow","gift bow","shoelace","reading glasses","infinity"},
  {"flag of oman","oman flag","flag oman","omani flag","muscat","sultanate of oman","the flag of oman"},
  {"feastables","feastables bar","feastable","chocolate bar","chocolate","mrbeast bar","candy bar"},
  {"brown square","rectangle","red rectangle","terracotta","maroon square","brown rectangle","red square","closed book","notebook","red brick","brick wall","chocolate bar","front door","red carpet","textbook","orange square"},
  {"mosquito net","file cabinet","filing cabinet","picture frame","framed picture","windows","window pane","window screen","card index","mosquito","solar panel","two windows","bookcase","drawers","chest of drawers"},
  {"american barn","american flag","flag united states","united states","america","farmhouse","stars and stripes","us flag and barn","old glory"},
  {"column chart","chart decreasing","down arrow","decreasing chart","downwards arrow","chart increasing","bar chart down","arrow and chart","statistics","histogram"},
  {"cloud with snow","snow cloud","snowflake","snowstorm","snow shower","snowing cloud","light snow","snowy cloud"},
  {"face with tears of joy","tears of joy emoji","laughing crying face","crying laughing face","tears of joy face","laughing with tears","rolling on the floor laughing","laughing face with tears"},
  {"bald eagle","bubo ascalaphus","golden eagle","pharaoh eagle owl","american eagle","stone eagle","rock and eagle","eagle and rock","gold and eagle","egg and eagle","nugget and eagle"},
  {"swimsuit","one piece swimsuit","bathing suit","swimwear","swimming","tank top","arrowhead","spearhead","plumb bob"},
};
