/* generated by naming.py -- piece candidate names with plausibility ranks */
#define NP 14
static const char *PKEY[NP]={"calendar","gnome","africa","bow","oman","feast","rect","frames","barn","chart","snow","joy","eagle","p14"};
#define MAXOPT 24
static const int NOPT[NP]={19,18,20,18,7,8,19,24,13,15,12,10,15,15};
static const int OR_[NP][MAXOPT]={
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17},
  {0,1,2,3,4,5,6},
  {0,1,2,3,4,5,6,7},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23},
  {0,1,2,3,4,5,6,7,8,9,10,11,12},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14},
  {0,1,2,3,4,5,6,7,8,9,10,11},
  {0,1,2,3,4,5,6,7,8,9},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14},
  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14},
};
static const char OL_[NP][MAXOPT]={
  {'A','H','E','A','E','O','A','M','H','W','O','P','E','D','E','A','A','I','L'},
  {'A','A','H','H','L','I','A','A','O','O','N','H','O','H','O','I','H','A'},
  {'T','O','I','H','T','I','S','D','E','U','E','A','N','A','T','I','T','I','T','A'},
  {'S','E','L','T','L','B','B','L','N','T','A','E','O','I','I','E','N','L'},
  {'F','L','M','F','T','N','A'},
  {'A','A','A','L','L','S','B','A'},
  {'S','N','C','C','N','R','U','L','L','A','D','O','I','W','D','R','O','E','B'},
  {'T','B','C','E','P','E','S','P','S','S','D','T','A','A','D','S','E','S','F','R','O','T','R','D'},
  {'A','A','D','S','A','U','N','A','R','N','A','D','I'},
  {'H','A','C','O','D','I','I','T','D','D','C','D','T','R','L'},
  {'H','D','E','M','E','W','S','T','L','U','C','O'},
  {'E','Y','Y','R','G','O','I','E','T','A'},
  {'G','E','E','A','E','N','G','N','C','H','A','D','D','A','E'},
  {'I','E','E','P','O','P','L','T','C','G','A','N','H','A','S'},
};
static const char OB_[NP][MAXOPT]={
  {'E','I','E','E','K','E','E','S','I','N','I','R','R','E','E','P','L','R','A'},
  {'E','E','L','N','E','D','S','F','E','E','R','L','F','I','M','E','R','U'},
  {'N','R','C','T','L','N','A','G','Y','R','I','H','E','C','R','B','N','N','N','L'},
  {'S','F','S','C','S','W','W','C','T','C','H','L','B','B','G','R','T','C'},
  {'O','F','O','I','A','A','L'},
  {'A','A','A','L','L','S','B','A'},
  {'U','L','A','T','Q','C','R','T','T','L','O','K','K','L','O','E','K','Q','O'},
  {'M','F','F','P','F','P','W','W','W','W','C','M','S','S','T','B','B','D','C','S','R','A','M','S'},
  {'R','R','G','T','R','M','R','L','G','B','R','N','G'},
  {'A','M','R','W','A','N','C','D','C','A','R','S','A','A','B'},
  {'D','C','F','S','S','T','D','Y','I','Y','F','E'},
  {'O','E','J','G','G','D','E','F','L','I'},
  {'E','G','G','E','G','E','E','R','L','A','L','A','A','D','G'},
  {'?','?','?','?','?','?','?','?','?','?','?','?','?','?','?'},
};
static const char *ONM[NP][MAXOPT]={
  {"calendar","christmas","december","calendar page","desk calendar","notepad","date","xmas","christmas day","twenty fifth","holiday","spiral calendar","tear off calendar","advent calendar","december twenty five","day planner","wall calendar","diary","almanac"},
  {"santas helper","garden gnome","christmas elf","christmas gnome","elf on the shelf","gingerbread man","father christmas","garden dwarf","roller skate","roller skater","snowboarder","christmas elves","woodland elf","christmas figure","holiday gnome","little helper","christmas ornament","garden statue"},
  {"continent","map of africa","african continent","silhouette","potted plant","africa and plant","houseplant","seedling","greenery","shrubbery","vegetation","savannah","rainforest","madagascar","south africa","african bush","thatching","africa and bush","continent of africa","map and plant"},
  {"glasses","butterfly","eyeglasses","spectacles","sunglasses","hair bow","gift bow","shoelaces","infinity","moustache","mustache","propeller","ribbon bow","bow ribbon","reading glasses","eyewear","bowknot","shoelace bow"},
  {"flag of oman","oman flag","flag oman","omani flag","muscat","sultanate of oman","the flag of oman"},
  {"feastables","feastables bar","feastable","chocolate bar","chocolate","mrbeast bar","candy bar","feastables chocolate"},
  {"brown square","rectangle","red rectangle","terracotta","maroon square","brown rectangle","red square","chocolate","chocolate bar","clay tablet","closed book","notebook","red brick","brick wall","front door","red carpet","textbook","orange square","brown block"},
  {"mosquito net","file cabinet","filing cabinet","picture frame","framed picture","picture frames","windows","window pane","window screen","window screens","card index","mosquito","solar panel","solar panels","two windows","bookcase","bookshelf","drawers","chest of drawers","speakers","radiator","air vent","mesh screen","screen door"},
  {"american barn","american flag","flag and barn","united states","america","farmhouse","stars and stripes","us flag and barn","old glory","red barn","american farm","barn and flag","flag united states"},
  {"column chart","histogram","chart decreasing","down arrow","downward arrow","decreasing","statistics","bar chart down","arrow and chart","graph and arrow","chart increasing","downwards arrow","bar chart and arrow","column graph","vertical bar chart"},
  {"cloud with snow","snow cloud","snowflake","snowstorm","snow shower","light snow","cloud and snow","snowy weather","snowing cloud","snowy cloud","snowfall cloud","winter cloud"},
  {"face with tears of joy","tears of joy face","tears of joy emoji","laughing crying face","crying laughing face","laughing so hard","laughing with tears","laughing tears face","rolling on the floor laughing","laughing face with tears"},
  {"bald eagle","golden egg","golden eagle","american eagle","egg and eagle","eagle and egg","gold nugget","eagle and rock","bubo ascalaphus","pharaoh eagle owl","stone eagle","rock and eagle","gold and eagle","nugget and eagle","golden egg and eagle"},
  {"swimsuit","arrowhead","spearhead","tank top","plumb bob","guitar pick","triangle","pendant","one piece swimsuit","bathing suit","swimwear","swimming","black shape","dark shape","shield shape"},
};
